name: mariposa_bulma
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  mariposa: ^1.1.0-alpha
dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  mariposa_test: ^1.0.0
  test: ^1.0.0